stages:
  - build
  - deploy

build-assets:
  image: "node:16.16.0-alpine"
  stage: build
  artifacts:
    paths:
      - ./
  script:
    - npm ci
    - npm run build

deploy-s3:dev:
  image: "node:16.16.0-alpine"
  environment:
    name: dev
  stage: deploy
  dependencies:
    - build-assets
  before_script:
    - apk add --no-cache python3 py3-pip && pip3 install --upgrade pip && pip3 install --no-cache-dir awscli
  script:
    - npm run deploy

deploy-s3:prod:
  environment:
    name: prod
  image: "node:16.16.0-alpine"
  stage: deploy
  dependencies:
    - build-assets
  before_script:
    - apk add --no-cache python3 py3-pip && pip3 install --upgrade pip && pip3 install --no-cache-dir awscli
  script:
    - npm run deploy
